Pum03 013
PUM03-2023/responsive-digital-library pull request #38
Opened 2023-03-16 16:52 UTC by lukasmoen

Använder npm react-contenteditable module, är det något som borde läggas in i typ dockerfilen? 
Det finns ingen edit för bild eller ISBN för tänker att det inte ska behövas, iaf inte på ett tag.

2023-04-03 07:28 UTC, tavro commented on client/src/App.js
> +    if(!window.localStorage.getItem('account')){
Jag tror tanken är att kolla om account finns i local storage här, inte tvärt om.

2023-04-03 07:30 UTC, tavro requested changes
Det ser bra ut överlag, men se över useEffect i App.js

2023-04-05 12:04 UTC, lukasmoen commented
Fixat local storage check för account, och lagt till contenteditable i json

2023-04-10 08:25 UTC, tavro commented
Bra jobbat!

2023-04-10 08:26 UTC, merged